name: Tests

on: push

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.5', '8.4']
                include:
                    - php-versions: '8.4'
                      build-assets: 1

        steps:
            - uses: actions/checkout@v6

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Cache Composer packages
              id: composer-cache
              uses: actions/cache@v5
              with:
                  path: vendor
                  key: ${{ runner.os }}-${{ matrix.php-versions }}

            - name: Install dependencies
              run: |
                composer config --no-plugins allow-plugins.composer/installers true
                composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
                composer update --prefer-dist --no-progress

            - name: Validate PHP syntax Part 1
              # The usage of bash + || exit 1 is to ensure xargs does not exit on first error.
              run: find ./ -maxdepth 1 -name '*.php' | xargs -n1 bash -c 'php -lf $0 || exit 1'

            - name: Validate PHP syntax Part 2
              # The usage of bash + || exit 1 is to ensure xargs does not exit on first error.
              run: find app/ views/ \( -name '*.php' \) | xargs -n1 bash -c 'php -lf $0 || exit 1'

            - name: Install Node.js
              if: ${{ matrix.build-assets }}
              uses: actions/setup-node@v6
              with:
                  node-version: 20

            - name: Install PNPM
              if: ${{ matrix.build-assets }}
              run: npm install -g pnpm@latest-10

            - name: Install Node dependencies
              if: ${{ matrix.build-assets }}
              run: pnpm install

            - name: Build assets
              if: ${{ matrix.build-assets }}
              run: pnpm build

            - name: Lint assets
              if: ${{ matrix.build-assets }}
              run: pnpm lint
